version: "3.8"

services:
  web:
    build: .
    container_name: news-management-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: news-management-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_management3
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/news_manamement3.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
